name: Executar Motor VidSrc

on:
  workflow_dispatch:

jobs:
  run-engine:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # Atualizado para a versão exigida pelo GitHub

      - name: Instalar dependências
        run: npm install

      - name: Rodar o Motor
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npm start

      - name: Salvar os JSONs
        run: |
          git config --global user.name 'Motor VidSrc Bot'
          git config --global user.email 'bot@cartoonzine.com'
          git add movies.json series.json
          # O comando abaixo evita erro caso a lista seja exatamente igual à anterior
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto: Atualizando listas VidSrc + TMDB" && git push)
